CREATE TABLE IF NOT EXISTS EXPECTED_RELEASES (
    RELEASE_ID INT PRIMARY KEY,
    TITLE STRING,
    ARTIST STRING,
    LABEL_NAME STRING,
    RELEASE_DATE DATE,
    GENRE STRING,
    EXPECTED_ALBUM_EQUIVALENT FLOAT,
    IS_RELEASED BOOLEAN
);
