CREATE TABLE IF NOT EXISTS EXPECTED_RELEASES (
    RELEASE_ID INTEGER PRIMARY KEY,
    MRELG_ID STRING,
    TITLE TEXT,
    ARTIST TEXT,
    LABEL_NAME TEXT,
    RELEASE_DATE DATE,
    GENRE STRING,
    EXPECTED_ALBUM_EQUIVALENT FLOAT,
    IS_RELEASED BOOLEAN,
    SCENARIO TEXT,
    KNOWN_VOLS TEXT,
    FY_VOL REAL,
    AVG_HISTORICAL_W1_PRODUCT_RATIO REAL,
    PRODUCT_RATIO_COEFFICIENT REAL,
    CLUSTER INTEGER
);
