CREATE TABLE IF NOT EXISTS STREAMING_ROSTER_2026 (
    MRELG_ID TEXT PRIMARY KEY,
    PRODUCT_TYPE TEXT,
    TITLE TEXT,
    ARTIST TEXT,
    LABEL_NAME TEXT,
    PARENT_GROUP TEXT,
    RELEASE_DATE TEXT,
    CREATED_AT TEXT DEFAULT (datetime('now'))
);
