CREATE TABLE IF NOT EXISTS MARKETSHARE_YTD (
    WEEK_ENDING_DATE DATE,
    YEAR INT,
    WEEK_NUM INT,
    COUNTRY_CODE STRING,
    RELEASE_AGE STRING,
    LABEL_NAME STRING,
    STREAMING_TOTAL INT,
    ALBUM_EQUIVALENT FLOAT,
    PRODUCT_SALES FLOAT,
    SONG_SALE_EQUIVALENT FLOAT,
    STREAMING_EQUIVALENT FLOAT,
    ALBUM_EQUIVALENT_SHARE FLOAT,
    PRODUCT_SALES_SHARE	FLOAT,
    SONG_SALE_EQUIVALENT_SHARE FLOAT,
    STREAMING_EQUIVALENT_SHARE FLOAT,
    UNIQUE (WEEK_ENDING_DATE, YEAR, WEEK_NUM, COUNTRY_CODE, RELEASE_AGE, LABEL_NAME)
);
