CREATE TABLE IF NOT EXISTS MARKETSHARE_RELEASE_METRICS (
    RELEASE_ID INT PRIMARY KEY,
    MRELG_ID STRING,
    WEEK_ENDING_DATE DATE,
    ALBUM_EQUIVALENT FLOAT,
    PRODUCT_SALES FLOAT,
    SONG_SALE_EQUIVALENT FLOAT,
    STREAMING_EQUIVALENT FLOAT,
    UNIQUE (RELEASE_ID, MRELG_ID, WEEK_ENDING_DATE)
)
