-- Weekly worldwide on-demand streams per MRELG (global_streaming forecast input).
CREATE TABLE IF NOT EXISTS MARKETSHARE_WEEKLY_GLOBAL_STREAMS (
    MRELG_ID TEXT NOT NULL,
    WEEK_ENDING_DATE TEXT NOT NULL,
    GLOBAL_STREAMS REAL,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (MRELG_ID, WEEK_ENDING_DATE)
);
