-- One current PPR per Luminate artist (nightly rewrite + live upsert).
CREATE TABLE IF NOT EXISTS ARTIST_PPR_CURRENT (
    LUMINATE_ARTIST_ID TEXT PRIMARY KEY NOT NULL,
    SODATONE_ARTIST_ID TEXT,
    PPR_VALUE REAL,
    CALCULATION_DATE TEXT,
    SOURCE TEXT,
    UPDATED_AT TEXT
) WITHOUT ROWID;
