-- One row per IC level-2 distributor (snapshot LABEL_NAME), rolled up from
-- MARKETSHARE_SEARCH_SUMMARY*. Typeahead hits this table only.
CREATE TABLE IF NOT EXISTS MARKETSHARE_SEARCH_DISTRIBUTORS (
    LEVEL_2_DISTRIBUTOR TEXT PRIMARY KEY NOT NULL,
    LABEL_SEARCH TEXT,
    DAILY_GLOBAL_STREAMS INTEGER,
    RELEASE_COUNT INTEGER
) WITHOUT ROWID;
