CREATE TABLE IF NOT EXISTS MARKETSHARE_RELEASE_METRICS (
    RELEASE_ID INTEGER NOT NULL,
    MRELG_ID TEXT,
    WEEK_ENDING_DATE DATE NOT NULL,
    ALBUM_EQUIVALENT REAL,
    PRODUCT_SALES REAL,
    SONG_SALE_EQUIVALENT REAL,
    STREAMING_EQUIVALENT REAL,
    UNIQUE (RELEASE_ID, WEEK_ENDING_DATE)
);
