INSERT INTO ARTIST_PPR_BY_RELEASE (
    MRELG_ID,
    LUMINATE_ARTIST_ID,
    ARTIST_INDEX,
    PPR_VALUE,
    CALCULATION_DATE
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(MRELG_ID, LUMINATE_ARTIST_ID)
DO UPDATE SET
    ARTIST_INDEX     = excluded.ARTIST_INDEX,
    PPR_VALUE        = excluded.PPR_VALUE,
    CALCULATION_DATE = excluded.CALCULATION_DATE
;
