INSERT INTO STREAMING_ROSTER_2026 (
    MRELG_ID, PRODUCT_TYPE, TITLE, ARTIST, LABEL_NAME, RELEASE_DATE
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(MRELG_ID) DO UPDATE SET
    PRODUCT_TYPE = excluded.PRODUCT_TYPE,
    TITLE        = excluded.TITLE,
    ARTIST       = excluded.ARTIST,
    LABEL_NAME   = excluded.LABEL_NAME,
    RELEASE_DATE = excluded.RELEASE_DATE
;
