INSERT INTO MARKETSHARE_SEARCH_DISTRIBUTORS (
    LEVEL_2_DISTRIBUTOR, LABEL_SEARCH, DAILY_GLOBAL_STREAMS, RELEASE_COUNT
) VALUES (?, ?, ?, ?)
ON CONFLICT(LEVEL_2_DISTRIBUTOR)
DO UPDATE SET
    LABEL_SEARCH         = excluded.LABEL_SEARCH,
    DAILY_GLOBAL_STREAMS = excluded.DAILY_GLOBAL_STREAMS,
    RELEASE_COUNT        = excluded.RELEASE_COUNT
;
