INSERT INTO MARKETSHARE_WEEKLY_GLOBAL_STREAMS (
    MRELG_ID, WEEK_ENDING_DATE, GLOBAL_STREAMS
) VALUES (?, ?, ?)
ON CONFLICT(MRELG_ID, WEEK_ENDING_DATE) DO UPDATE SET
    GLOBAL_STREAMS = excluded.GLOBAL_STREAMS,
    UPDATED_AT = CURRENT_TIMESTAMP
;
