INSERT INTO MARKETSHARE_WEEKLY (
    WEEK_ENDING_DATE, COUNTRY_CODE, RELEASE_AGE, LABEL_NAME,
    STREAMING_TOTAL, ALBUM_EQUIVALENT, PRODUCT_SALES, SONG_SALE_EQUIVALENT,
    STREAMING_EQUIVALENT, ALBUM_EQUIVALENT_SHARE, PRODUCT_SALES_SHARE,
    SONG_SALE_EQUIVALENT_SHARE, STREAMING_EQUIVALENT_SHARE
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(WEEK_ENDING_DATE, COUNTRY_CODE, RELEASE_AGE, LABEL_NAME)
DO UPDATE SET
    STREAMING_TOTAL        = excluded.STREAMING_TOTAL,
    ALBUM_EQUIVALENT       = excluded.ALBUM_EQUIVALENT,
    PRODUCT_SALES          = excluded.PRODUCT_SALES,
    SONG_SALE_EQUIVALENT   = excluded.SONG_SALE_EQUIVALENT,
    STREAMING_EQUIVALENT   = excluded.STREAMING_EQUIVALENT,
    ALBUM_EQUIVALENT_SHARE = excluded.ALBUM_EQUIVALENT_SHARE,
    PRODUCT_SALES_SHARE    = excluded.PRODUCT_SALES_SHARE,
    SONG_SALE_EQUIVALENT_SHARE       = excluded.SONG_SALE_EQUIVALENT_SHARE,
    STREAMING_EQUIVALENT_SHARE        = excluded.STREAMING_EQUIVALENT_SHARE
;