INSERT INTO ARTIST_PPR_CURRENT (
    LUMINATE_ARTIST_ID,
    SODATONE_ARTIST_ID,
    PPR_VALUE,
    CALCULATION_DATE,
    SOURCE,
    UPDATED_AT
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(LUMINATE_ARTIST_ID)
DO UPDATE SET
    SODATONE_ARTIST_ID = excluded.SODATONE_ARTIST_ID,
    PPR_VALUE          = excluded.PPR_VALUE,
    CALCULATION_DATE   = excluded.CALCULATION_DATE,
    SOURCE             = excluded.SOURCE,
    UPDATED_AT         = excluded.UPDATED_AT
;
