INSERT INTO MARKETSHARE_DAILY_GLOBAL_STREAMS (
    MRELG_ID, REPORT_DATE, GLOBAL_STREAMS
) VALUES (?, ?, ?)
ON CONFLICT(MRELG_ID, REPORT_DATE)
DO UPDATE SET
    GLOBAL_STREAMS = excluded.GLOBAL_STREAMS,
    UPDATED_AT = CURRENT_TIMESTAMP
;
