INSERT INTO MARKETSHARE_RELEASE_METRICS (
    RELEASE_ID, MRELG_ID, WEEK_ENDING_DATE, ALBUM_EQUIVALENT, PRODUCT_SALES, SONG_SALE_EQUIVALENT, STREAMING_EQUIVALENT
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(RELEASE_ID, WEEK_ENDING_DATE)
DO UPDATE SET
    ALBUM_EQUIVALENT = excluded.ALBUM_EQUIVALENT,
    PRODUCT_SALES = excluded.PRODUCT_SALES,
    SONG_SALE_EQUIVALENT = excluded.SONG_SALE_EQUIVALENT,
    STREAMING_EQUIVALENT = excluded.STREAMING_EQUIVALENT
;