INSERT INTO MARKETSHARE_SEARCH_ARTISTS (
    LUMINATE_ARTIST_ID, ARTIST, ARTIST_SEARCH, DAILY_GLOBAL_STREAMS,
    RELEASE_COUNT, HAS_ARTWORK
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(LUMINATE_ARTIST_ID)
DO UPDATE SET
    ARTIST               = excluded.ARTIST,
    ARTIST_SEARCH        = excluded.ARTIST_SEARCH,
    DAILY_GLOBAL_STREAMS = excluded.DAILY_GLOBAL_STREAMS,
    RELEASE_COUNT        = excluded.RELEASE_COUNT,
    HAS_ARTWORK          = excluded.HAS_ARTWORK
;
