-- Artist-page discography: albums, EPs, and singles for one LUMINATE_ARTIST_ID.
-- PRODUCT_TYPE comes from the snapshot RELEASE_TYPE (Album / EP / Single).
-- Both ? placeholders are the same artist id.
SELECT
    MRELG_ID,
    TITLE,
    ARTIST,
    COALESCE(NULLIF(TRIM(RELEASE_TYPE), ''), 'Album') AS PRODUCT_TYPE,
    RELEASE_DATE,
    DAILY_GLOBAL_STREAMS,
    LABEL_NAME AS LEVEL_2_DISTRIBUTOR
FROM MARKETSHARE_SEARCH_SUMMARY
WHERE LUMINATE_ARTIST_ID = ?
UNION ALL
SELECT
    MRELG_ID,
    TITLE,
    ARTIST,
    COALESCE(NULLIF(TRIM(RELEASE_TYPE), ''), 'Single') AS PRODUCT_TYPE,
    RELEASE_DATE,
    DAILY_GLOBAL_STREAMS,
    LABEL_NAME AS LEVEL_2_DISTRIBUTOR
FROM MARKETSHARE_SEARCH_SUMMARY_SINGLES
WHERE LUMINATE_ARTIST_ID = ?
ORDER BY DAILY_GLOBAL_STREAMS DESC, RELEASE_DATE DESC, MRELG_ID
;