-- Typeahead over MARKETSHARE_SEARCH_DISTRIBUTORS (pre-aggregated).
-- LIKE placeholders are the same pattern; LIMIT is last.
SELECT
    LEVEL_2_DISTRIBUTOR,
    RELEASE_COUNT,
    DAILY_GLOBAL_STREAMS
FROM MARKETSHARE_SEARCH_DISTRIBUTORS
WHERE LABEL_SEARCH LIKE ? ESCAPE '\'
ORDER BY DAILY_GLOBAL_STREAMS DESC, LEVEL_2_DISTRIBUTOR COLLATE NOCASE
LIMIT ?
;
