-- Distinct IC level-2 distributors from album + singles search snapshots.
SELECT
    LABEL_NAME AS LEVEL_2_DISTRIBUTOR,
    COALESCE(SUM(DAILY_GLOBAL_STREAMS), 0) AS DAILY_GLOBAL_STREAMS,
    COUNT(*) AS RELEASE_COUNT
FROM (
    SELECT LABEL_NAME, COALESCE(DAILY_GLOBAL_STREAMS, 0) AS DAILY_GLOBAL_STREAMS
    FROM MARKETSHARE_SEARCH_SUMMARY
    WHERE LABEL_NAME IS NOT NULL
      AND TRIM(LABEL_NAME) != ''
    UNION ALL
    SELECT LABEL_NAME, COALESCE(DAILY_GLOBAL_STREAMS, 0)
    FROM MARKETSHARE_SEARCH_SUMMARY_SINGLES
    WHERE LABEL_NAME IS NOT NULL
      AND TRIM(LABEL_NAME) != ''
)
GROUP BY LABEL_NAME
;
