UPDATE EXPECTED_RELEASES SET
    MRELG_ID = ?,
    TITLE = ?,
    ARTIST = ?,
    LABEL_NAME = ?,
    RELEASE_DATE = ?,
    GENRE = ?,
    EXPECTED_ALBUM_EQUIVALENT = ?,
    IS_RELEASED = ?,
    SCENARIO = ?,
    KNOWN_VOLS = ?,
    FY_VOL = ?,
    AVG_HISTORICAL_W1_PRODUCT_RATIO = ?,
    PRODUCT_RATIO_COEFFICIENT = ?,
    CLUSTER = ?
WHERE RELEASE_ID = ?;
