INSERT INTO EXPECTED_RELEASES (
    MRELG_ID, TITLE, ARTIST, LABEL_NAME, RELEASE_DATE, GENRE, PRODUCT_TYPE,
    EXPECTED_ALBUM_EQUIVALENT,
    FW_STREAMS, FW_SONGS, FW_SALES,
    SCENARIO, FY_VOL, AVG_HISTORICAL_W1_PRODUCT_RATIO,
    PRODUCT_RATIO_COEFFICIENT, CLUSTER
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING RELEASE_ID;
