INSERT INTO EXPECTED_RELEASES (
    MRELG_ID, TITLE, ARTIST, LABEL_NAME, RELEASE_DATE, GENRE,
    EXPECTED_ALBUM_EQUIVALENT, IS_RELEASED,
    SCENARIO, KNOWN_VOLS, FY_VOL,
    AVG_HISTORICAL_W1_PRODUCT_RATIO, PRODUCT_RATIO_COEFFICIENT, CLUSTER
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING RELEASE_ID;
