SELECT
    WEEK_ENDING_DATE,
    LABEL_NAME,
    ALBUM_EQUIVALENT,
    ALBUM_EQUIVALENT_SHARE
FROM MARKETSHARE_WEEKLY
WHERE
    LABEL_NAME IN ('Atlantic Music Group', 'Interscope/Geffen/A&M')
    AND COUNTRY_CODE = 'US'
    AND RELEASE_AGE = 'Current'
ORDER BY date(WEEK_ENDING_DATE) ASC;
