SELECT
    MRELG_ID,
    PRODUCT_TYPE,
    TITLE,
    ARTIST,
    LUMINATE_ARTIST_ID,
    LABEL_NAME,
    PARENT_GROUP,
    RELEASE_DATE
FROM STREAMING_ROSTER_2026
ORDER BY RELEASE_DATE DESC, MRELG_ID
;
